#
#    Copyright (c) 2026 Manuel Hilgert
#
#    See the file LICENSE for your full rights.
#
"""Build the field catalog from Werner Krenn's ecowittcustom driver.

The catalog is data, not code, and it should stay traceable to where it came from.
Rather than retyping five hundred field names, this reads them out of the source with
the ast module and writes catalog.py.

Usage:

    python tools/import_catalog.py path/to/ecowittcustom.py

The result is reviewed and committed like any other file. Run it again when upstream
adds fields, and the diff shows exactly what changed.
"""

import argparse
import ast
import os.path
import re
import sys

HEADER = '''#
#    Copyright (c) 2016-2020 Matthew Wall
#    Copyright (c) 2025-2026 Werner Krenn
#    Copyright (c) 2026 Manuel Hilgert
#
#    See the file LICENSE for your full rights.
#
"""What the hardware sends, and where it belongs in WeeWX.

Generated by tools/import_catalog.py from the ecowittcustom driver by Werner Krenn,
https://github.com/WernerKr/Ecowitt-or-DAVIS-stations-and-Season-skin, which is itself
descended from the interceptor driver by Matthew Wall. Both are GPLv3, and so is this.

Do not edit by hand. Run the tool again instead, so that the next update upstream stays
a reviewable diff.

Source: {source}
Fields: {count}
"""

# Raw field name as the hardware sends it -> the WeeWX field it belongs in.
FIELDS = {{
{fields}}}

# WeeWX field -> unit group, for the fields that are not already in the WeeWX schema.
GROUPS = {{
{groups}}}

# Raw field prefixes whose target name says more than the hardware does. A reading from
# one of these is in the right unit and the right channel, but whether it belongs to
# soil, a pool or a wall is the user's to say, with field_map_extensions.
PLACEMENT_UNKNOWN = {{
{placement}}}
'''


# Families where the WeeWX field name claims something the hardware never said. These
# are multi-channel sensors: the same model reports on the same field whether it is a
# probe in a flower bed, a silicone lead in a pool, or a sensor on a north wall. The
# mapping has to put them somewhere, and somewhere is not the same as knowing.
#
# This is hardware knowledge, so it cannot be read out of the upstream source. It is
# kept here, next to the tool that writes the catalog.
PLACEMENT_UNKNOWN = {
    'tf_ch': "WN34 multi-channel temperature. Sold as a soil probe, a pool lead, and "
             "for indoor or outdoor use. All of them report as tf_chN. They are mapped "
             "to soilTemp because extraTemp is already taken by the WH31.",
    'temp': "WH31 multi-channel temperature and humidity. Placement is the user's.",
    'leafwetness_ch': "WN35 leaf wetness. Placement is the user's.",
}

# Where we knowingly differ from upstream, and why. Each of these is a decision, so it
# is written down rather than left in a commit message.
OVERRIDES = {
    # Upstream puts the time of the last strike into lightning_disturber_count, which
    # counts something else entirely. A Unix timestamp in a counter shows up in reports
    # as a ten digit number of strikes.
    'lightning_time': 'lightning_time',
}


def find_class(node, name):
    for child in ast.walk(node):
        if isinstance(child, ast.ClassDef) and child.name == name:
            return child
    raise SystemExit("Cannot find class %s" % name)


def const_assign(class_node, name):
    for statement in class_node.body:
        if isinstance(statement, ast.Assign) \
                and any(getattr(t, 'id', None) == name for t in statement.targets):
            return ast.literal_eval(statement.value)
    raise SystemExit("Cannot find %s" % name)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', help="Path to ecowittcustom.py")
    parser.add_argument('--out', default='bin/user/ecowitt/catalog.py')
    parser.add_argument('--schema', help="Path to WeeWX's wview_extended.py. Used to "
                                         "settle which target wins when upstream maps "
                                         "one reading to more than one field.")
    args = parser.parse_args()

    schema_fields = set()
    if args.schema:
        with open(args.schema, encoding='utf-8') as fd:
            schema_fields = set(re.findall(r"\('(\w+)',\s+'\w+'\)", fd.read()))

    with open(args.source, encoding='utf-8', errors='replace') as fd:
        source = fd.read()
    tree = ast.parse(source)

    # Raw field -> intermediate name, from the Ecowitt parser.
    label_map = const_assign(find_class(find_class(tree, 'EcowittClient'), 'Parser'),
                             'LABEL_MAP')
    # WeeWX field -> intermediate name, from the shared consumer.
    sensor_map = const_assign(find_class(tree, 'Consumer'), 'DEFAULT_SENSOR_MAP')
    # WeeWX field -> unit group, assigned at import time in the driver.
    groups = dict(re.findall(r"^weewx\.units\.obs_group_dict\['([^']+)'\]\s*=\s*'([^']+)'",
                             source, re.M))

    # The two maps meet in the middle, at the intermediate name. Collapse them, so that
    # a lookup here is one step rather than two.
    by_intermediate = {}
    for weewx_field, intermediate in sensor_map.items():
        by_intermediate.setdefault(intermediate, []).append(weewx_field)

    fields = {}
    unresolved = []
    ambiguous = []
    for raw, intermediate in sorted(label_map.items()):
        if raw in OVERRIDES:
            fields[raw] = OVERRIDES[raw]
            continue
        targets = by_intermediate.get(intermediate)
        if not targets:
            unresolved.append(raw)
            continue
        if len(targets) > 1:
            # A schema field wins, because that is what skins and reports look for. A
            # battery on outTempBatteryStatus shows up in the Seasons sensor panel; the
            # same reading on wh65_batt does not.
            preferred = sorted(t for t in targets if t in schema_fields)
            if preferred:
                chosen = preferred[0]
            elif raw in targets:
                # No schema field to settle it, but one target is the raw name itself.
                # Prefer that over a variant spelling of it.
                chosen = raw
            else:
                chosen = sorted(targets)[0]
            ambiguous.append((raw, chosen, sorted(set(targets) - {chosen})))
            fields[raw] = chosen
        else:
            fields[raw] = targets[0]

    used_groups = {f: g for f, g in sorted(groups.items()) if f in set(fields.values())}

    def render(mapping):
        # repr, not quotes of our own: some of these values contain an apostrophe.
        return ''.join("    %r: %r,\n" % (k, v) for k, v in sorted(mapping.items()))

    with open(args.out, 'w', encoding='utf-8', newline='\n') as fd:
        fd.write(HEADER.format(source=os.path.basename(args.source),
                               count=len(fields),
                               fields=render(fields),
                               groups=render(used_groups),
                               placement=render(PLACEMENT_UNKNOWN)))

    print("%d fields, %d unit groups -> %s" % (len(fields), len(used_groups), args.out))
    if OVERRIDES:
        print("%d fields differ from upstream on purpose: %s"
              % (len(OVERRIDES), ' '.join(sorted(OVERRIDES))))
    if ambiguous:
        print("%d readings had more than one target upstream:" % len(ambiguous))
        for raw, chosen, rest in ambiguous:
            print("  %-22s -> %-24s (not %s)" % (raw, chosen, ', '.join(rest)))
    if unresolved:
        print("%d raw fields have no WeeWX target upstream, left out:" % len(unresolved),
              file=sys.stderr)
        print("  " + ' '.join(unresolved), file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
